name: ffbdev-homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.7.2
    restart: unless-stopped
    container_name: homepage
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /app/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: homepage
  description:
    en_us: |
      A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations
      for over 100 services and translations into multiple languages. Easily configured via YAML files or through
      docker label discovery.
  tagline:
    en_us: ""
  developer: "Ben Phelps"
  author: "Frederico Freire Boaventura"
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homepage.png
  thumbnail: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homepage.png
  title:
    en_us: Homepage
  category: Utilities
